In [4]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns',None)
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [12]:
import os
path='D:\Python\TheQuibits\Zero-shield-main\Zero-shield-main_main - Copy\ml_models\Datasets\CICIDS'
os.chdir(path)

In [13]:
df1 = pd.read_csv('Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv')
df2 = pd.read_csv('Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv')
df3 = pd.read_csv('Friday-WorkingHours-Morning.pcap_ISCX.csv')
df4 = pd.read_csv('Monday-WorkingHours.pcap_ISCX.csv')
df5 = pd.read_csv('Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv')
df6 = pd.read_csv('Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv')
df7 = pd.read_csv('Tuesday-WorkingHours.pcap_ISCX.csv')
df8 = pd.read_csv('Wednesday-workingHours.pcap_ISCX.csv')

In [14]:
df = pd.concat([df1,df2])
# del df1,df2
df = pd.concat([df,df3])
# del df3
df = pd.concat([df,df4])
# del df4
df = pd.concat([df,df5])
# del df5/
df = pd.concat([df,df6])
# del df6
df = pd.concat([df,df7])
# del df7
df = pd.concat([df,df8])
# del df8
df.shape

(2830743, 79)

In [15]:
df.columns

Index([' Destination Port', ' Flow Duration', ' Total Fwd Packets',
       ' Total Backward Packets', 'Total Length of Fwd Packets',
       ' Total Length of Bwd Packets', ' Fwd Packet Length Max',
       ' Fwd Packet Length Min', ' Fwd Packet Length Mean',
       ' Fwd Packet Length Std', 'Bwd Packet Length Max',
       ' Bwd Packet Length Min', ' Bwd Packet Length Mean',
       ' Bwd Packet Length Std', 'Flow Bytes/s', ' Flow Packets/s',
       ' Flow IAT Mean', ' Flow IAT Std', ' Flow IAT Max', ' Flow IAT Min',
       'Fwd IAT Total', ' Fwd IAT Mean', ' Fwd IAT Std', ' Fwd IAT Max',
       ' Fwd IAT Min', 'Bwd IAT Total', ' Bwd IAT Mean', ' Bwd IAT Std',
       ' Bwd IAT Max', ' Bwd IAT Min', 'Fwd PSH Flags', ' Bwd PSH Flags',
       ' Fwd URG Flags', ' Bwd URG Flags', ' Fwd Header Length',
       ' Bwd Header Length', 'Fwd Packets/s', ' Bwd Packets/s',
       ' Min Packet Length', ' Max Packet Length', ' Packet Length Mean',
       ' Packet Length Std', ' Packet Length Variance', '

In [16]:
df.isnull().sum().sort_values(ascending = False)
df.dropna(inplace=True)
df.isnull().sum().sort_values(ascending = False)

 Destination Port        0
 ECE Flag Count          0
 Fwd Avg Packets/Bulk    0
Fwd Avg Bytes/Bulk       0
 Fwd Header Length.1     0
                        ..
Bwd IAT Total            0
 Fwd IAT Min             0
 Fwd IAT Max             0
 Fwd IAT Std             0
 Label                   0
Length: 79, dtype: int64

In [17]:
originals = list(df[' Label'].unique())
originals

['BENIGN',
 'DDoS',
 'PortScan',
 'Bot',
 'Infiltration',
 'Web Attack � Brute Force',
 'Web Attack � XSS',
 'Web Attack � Sql Injection',
 'FTP-Patator',
 'SSH-Patator',
 'DoS slowloris',
 'DoS Slowhttptest',
 'DoS Hulk',
 'DoS GoldenEye',
 'Heartbleed']

In [18]:
print(df[' Label'].value_counts())

BENIGN                        2272688
DoS Hulk                       230124
PortScan                       158930
DDoS                           128027
DoS GoldenEye                   10293
FTP-Patator                      7938
SSH-Patator                      5897
DoS slowloris                    5796
DoS Slowhttptest                 5499
Bot                              1966
Web Attack � Brute Force         1507
Web Attack � XSS                  652
Infiltration                       36
Web Attack � Sql Injection         21
Heartbleed                         11
Name:  Label, dtype: int64


In [19]:
def targetify(i):
    if i == 'BENIGN':
        return 0
    else:
        return 1

In [20]:
df[" Label"] = df[" Label"].apply(targetify)
print(df[' Label'].value_counts())


0    2272688
1     556697
Name:  Label, dtype: int64


In [21]:
df[' Label'].unique()

array([0, 1], dtype=int64)

In [22]:
df[' Label'].value_counts()

0    2272688
1     556697
Name:  Label, dtype: int64

In [23]:
print(df.shape)
df=df.drop_duplicates(keep='first')
print(df.shape)

(2829385, 79)
(2522009, 79)


In [24]:
df = df[~df.isin([np.nan, np.inf, -np.inf]).any(1)]
df.shape

C:\Users\HP\AppData\Local\Temp\ipykernel_15048\789146936.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.any and Series.any will be keyword-only.
  df = df[~df.isin([np.nan, np.inf, -np.inf]).any(1)]


(2520798, 79)

In [25]:
crr=list(df.corr()[' Label'])
print(crr,"\n")
ls=[crr.index(i) for i in crr if abs(i)<0.01]
print(ls,"\n")

[-0.15960255729076697, 0.27900814297274273, -0.0030550685202469117, -0.003175640392710036, -0.015079011552927209, -0.002127195067598197, -0.049019358048620405, -0.13112368686685683, -0.07437716814267513, -0.026204060184124068, 0.5964718882005696, -0.26513451200472454, 0.5944125702997664, 0.6117193164573792, -0.022131470710685112, -0.06859141275968125, 0.2246124905646447, 0.4109717167458292, 0.47151959479735245, 0.018012919160030016, 0.2800692956396266, 0.1929963357134681, 0.5061101230900161, 0.47080034876379584, -0.021360911597259183, 0.0060896780582666695, 0.022218330357802706, 0.19791983541908903, 0.1464880325469376, -0.03239144379960784, -0.08182439079530555, nan, -0.0025395553250187356, nan, 0.0005928737574115953, 0.0007843304337794194, -0.07531171854373958, 0.01623754288426453, -0.2769490961764388, 0.5554739541003533, 0.5209495581330975, 0.5734866484673178, 0.5367758036606631, 0.2719442718540575, -0.08182439079530555, -0.007437499559446921, 0.1443626631616928, 0.10380014801756379,

In [26]:
colsfromindex = list(set(df.columns[ls]))
colsfromindex

[' Fwd Header Length',
 'Bwd IAT Total',
 ' Bwd Header Length',
 ' Subflow Bwd Bytes',
 ' Total Length of Bwd Packets',
 ' RST Flag Count',
 'Init_Win_bytes_forward',
 ' Total Fwd Packets',
 ' act_data_pkt_fwd',
 ' Active Max',
 ' Fwd URG Flags',
 ' ECE Flag Count',
 ' Total Backward Packets',
 ' min_seg_size_forward']

In [27]:
colsfromindex.remove(' Total Fwd Packets')
colsfromindex.remove(' Total Backward Packets')
colsfromindex.remove(' Total Length of Bwd Packets')
colsfromindex.remove(' RST Flag Count')
colsfromindex.remove('Bwd IAT Total')

In [28]:
colsfromindex

[' Fwd Header Length',
 ' Bwd Header Length',
 ' Subflow Bwd Bytes',
 'Init_Win_bytes_forward',
 ' act_data_pkt_fwd',
 ' Active Max',
 ' Fwd URG Flags',
 ' ECE Flag Count',
 ' min_seg_size_forward']

In [29]:
print(df.shape)
df.drop(colsfromindex, axis=1, inplace=True)
print(df.shape)

(2520798, 79)
(2520798, 70)


In [30]:
df.head()
traincols = list(df.columns)

In [31]:
x=df.drop([' Label'],axis=1)
y=df[' Label']
print(x.shape)
print(y.shape)

(2520798, 69)
(2520798,)


In [32]:
x_train,x_test,y_train,y_test = train_test_split(x,y)

In [33]:
x_train.shape

(1890598, 69)

In [34]:
x_train.head()

Destination Port   Flow Duration   Total Fwd Packets  \
276706                443         5338420                   9   
402296                 53          143087                   1   
15008                 443        91036702                  19   
15748                  53           23955                   2   
35441                  53           85427                   2   

         Total Backward Packets  Total Length of Fwd Packets  \
276706                        5                          354   
402296                        1                           42   
15008                        17                         1500   
15748                         2                           72   
35441                         2                           82   

         Total Length of Bwd Packets   Fwd Packet Length Max  \
276706                          3677                     197   
402296                           134                      42   
15008                           4909                     432   
15748                            246                      36   
35441                            216                      41   

         Fwd Packet Length Min   Fwd Packet Length Mean  \
276706                       0                39.333333   
402296                      42                42.000000   
15008                        0                78.947368   
15748                       36                36.000000   
35441                       41                41.000000   

         Fwd Packet Length Std  Bwd Packet Length Max   Bwd Packet Length Min  \
276706               72.216688                   1987                       0   
402296                0.000000                    134                     134   
15008               114.666412                   1460                       0   
15748                 0.000000                    123                     123   
35441                 0.000000                    108                     108   

         Bwd Packet Length Mean   Bwd Packet Length Std  Flow Bytes/s  \
276706               735.400000              921.869188    755.092331   
402296               134.000000                0.000000   1230.020896   
15008                288.764706              491.252294     70.400178   
15748                123.000000                0.000000  13274.890420   
35441                108.000000                0.000000   3488.358482   

         Flow Packets/s   Flow IAT Mean   Flow IAT Std   Flow IAT Max  \
276706         2.622499    4.106477e+05   1.420062e+06        5136469   
402296        13.977510    1.430870e+05   0.000000e+00         143087   
15008          0.395445    2.601049e+06   1.059092e+07       45003120   
15748        166.979754    7.985000e+03   1.378541e+04          23903   
35441         46.823604    2.847567e+04   4.927887e+04          85378   

         Flow IAT Min  Fwd IAT Total   Fwd IAT Mean   Fwd IAT Std  \
276706             38        5338420       667302.5  1.805976e+06   
402296         143087              0            0.0  0.000000e+00   
15008               1       91021527      5056751.5  1.453515e+07   
15748               4              4            4.0  0.000000e+00   
35441               1              1            1.0  0.000000e+00   

         Fwd IAT Max   Fwd IAT Min  Bwd IAT Total   Bwd IAT Mean  \
276706       5136469            49         137652      34413.000   
402296             0             0              0          0.000   
15008       45014125             1       91021602    5688850.125   
15748              4             4             48         48.000   
35441              1             1             48         48.000   

         Bwd IAT Std   Bwd IAT Max   Bwd IAT Min  Fwd PSH Flags  \
276706  4.061286e+04         85638           216              0   
402296  0.000000e+00             0             0              0   
15008   1.535256e+07      45018560             4              0   
15748   0.000000e+00            48  

In [35]:
y_train.shape

(1890598,)

In [36]:
y_train.head()

276706    0
402296    0
15008     0
15748     0
35441     0
Name:  Label, dtype: int64

In [37]:
x_test.head()

Destination Port   Flow Duration   Total Fwd Packets  \
208995              37840           14135                   3   
140912                443         2370041                  24   
572234              53101              49                   2   
132153                 53           24438                   1   
92777                  80          720760                   3   

         Total Backward Packets  Total Length of Fwd Packets  \
208995                        0                           12   
140912                       30                          831   
572234                        0                           12   
132153                        1                           47   
92777                         6                           26   

         Total Length of Bwd Packets   Fwd Packet Length Max  \
208995                             0                       6   
140912                         54196                     392   
572234                             0                       6   
132153                            79                      47   
92777                          11607                      20   

         Fwd Packet Length Min   Fwd Packet Length Mean  \
208995                       0                 4.000000   
140912                       0                34.625000   
572234                       6                 6.000000   
132153                      47                47.000000   
92777                        0                 8.666667   

         Fwd Packet Length Std  Bwd Packet Length Max   Bwd Packet Length Min  \
208995                3.464102                      0                       0   
140912               88.153923                   4230                       0   
572234                0.000000                      0                       0   
132153                0.000000                     79                      79   
92777                10.263203                   5840                       0   

         Bwd Packet Length Mean   Bwd Packet Length Std   Flow Bytes/s  \
208995                 0.000000                0.000000     848.956491   
140912              1806.533333             1103.267396   23217.741800   
572234                 0.000000                0.000000  244897.959200   
132153                79.000000                0.000000    5155.904739   
92777               1934.500000             2538.919278   16139.907880   

         Flow Packets/s   Flow IAT Mean   Flow IAT Std   Flow IAT Max  \
208995       212.239123      7067.50000    9990.711711          14132   
140912        22.784416     44717.75472  221046.664600        1601607   
572234     40816.326530        49.00000       0.000000             49   
132153        81.839758     24438.00000       0.000000          24438   
92777         12.486819     90095.00000  254502.314400         719956   

         Flow IAT Min  Fwd IAT Total   Fwd IAT Mean   Fwd IAT Std  \
208995              3          14135     7067.50000   9990.711711   
140912              3         768431    33410.04348  53629.850420   
572234             49             49       49.00000      0.000000   
132153          24438              0        0.00000      0.000000   
92777               3            498      249.00000    282.842713   

         Fwd IAT Max   Fwd IAT Min  Bwd IAT Total   Bwd IAT Mean  \
208995         14132             3              0        0.00000   
140912        131192           166        2239897    77237.82759   
572234            49            49              0        0.00000   
132153             0             0              0        0.00000   
92777            449            49         720713   144142.60000   

         Bwd IAT Std   Bwd IAT Max   Bwd IAT Min  Fwd PSH Flags  \
208995        0.0000             0             0              0   
140912   306397.1551       1650704             3              0   
572234        0.0000             0             0              0   
132153        0.0000          

In [38]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

# Load


# Create the random forest model
rf_model = RandomForestRegressor(n_estimators=100, max_features='sqrt', random_state=42)

# Fit the model on the training data
rf_model.fit(x_train, y_train)

# Predict on the testing data
y_pred = rf_model.predict(x_test)


In [39]:
# Calculate the mean squared error (MSE) and R-squared score
mse = np.mean((y_pred - y_test)**2)
r2 = rf_model.score(x_test, y_test)

# Print the results
print(f'Mean squared error: {mse:.2f}')
print(f'R-squared score: {r2:.2f}')

Mean squared error: 0.00
R-squared score: 0.99


In [40]:
print(y_pred)
y_predbin = (y_pred > 0.5).astype(int)
print(y_predbin)

[0. 0. 0. ... 0. 0. 0.]
[0 0 0 ... 0 0 0]


In [46]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Compute the evaluation metrics
accuracy = accuracy_score(y_test, y_predbin)
precision = precision_score(y_test, y_predbin)
recall = recall_score(y_test, y_predbin)
f1 = f1_score(y_test,y_predbin)
confusion_mat = confusion_matrix(y_test, y_predbin)

# Print the results
print('Accuracy:', accuracy)
print('Precision:', precision)
print('Recall:', recall)
print('F1 score:', f1)
print('Confusion matrix:\n', confusion_mat)


Accuracy: 0.998133925737861
Precision: 0.9954524912439272
Recall: 0.9934881885324462
F1 score: 0.994469369903214
Confusion matrix:
 [[523295    483]
 [   693 105729]]


In [47]:
path='D:\Python\TheQuibits\Zero-shield-main\Zero-shield-main_main - Copy\ml_models\saved_models'
os.chdir(path)

In [48]:
import pickle
with open("RandomForest", 'wb') as file:
    pickle.dump(rf_model, file)
file.close()